# Generated by Django 3.1.5 on 2021-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=142)),
                ('password', models.CharField(max_length=22)),
                ('confirmpassword', models.CharField(max_length=22)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
